export const defaultTextTemplates = [
  {
    text: '大标题',
    fontSize: '30px',
    fontFamily: '',
    fontWeight: 'bold',
    fontStyle: '',
    textDecoration: '',
    tag: 'h2',
    name: 'l-text',
    lineHeight: '1',
    textAlign: 'center',
    opacity: '1',
    borderStyle: 'solid',
  },
  {
    text: '正文内容',
    tag: 'p',
    name: 'l-text',
    textAlign: 'center',
    lineHeight: '1',
    opacity: '1',
    borderStyle: 'solid',
    fontSize: '30px',
    fontFamily: '',
    fontWeight: 'bold',
    fontStyle: '',
    textDecoration: '',
  },
  {
    text: '链接内容',
    color: '#1890ff',
    tag: 'p',
    name: 'l-text',
    textAlign: 'center',
    lineHeight: '1',
    opacity: '1',
    borderStyle: 'solid',
    fontSize: '30px',
    fontFamily: '',
    fontWeight: 'bold',
    fontStyle: '',
    textDecoration: '',
  },
  {
    text: '按钮内容',
    color: '#ffffff',
    backgroundColor: '#1890ff',
    borderWidth: '1px',
    borderColor: '#1890ff',
    borderStyle: 'solid',
    borderRadius: '2px',
    paddingLeft: '10px',
    paddingRight: '10px',
    paddingTop: '5px',
    paddingBottom: '5px',
    tag: 'button',
    textAlign: 'center',
    position: 'relative',
    name: 'l-text',
    fontSize: '30px',
  },
]
